---
output: pdf_document
---

#Load Libraries
```{r}
library(rworldmap)
library(ggplot2)
library(maps)
setwd('/Users/bobminnich/Documents/Columbia/edX Course')
```

```{r}
#Load Data
df = read.csv("Merged-1.csv", header=T)
# Get World map
worldmap <- map_data("state")
#Prepare the Borders
mapWorld <- borders("world", colour="dark blue", fill="black") 
# Draw the map and mapWorld to show background map
mp <- ggplot() +   mapWorld
#Plot points related to latitude and longitude, with the size and color based on the count
mp <- mp + geom_point(data = df, aes(x = Longitude, y = Latitude, size = count, color = count, label = country.name)) 
#Scale the color based on a gradient from yellow as low to orange as
mp <- mp + scale_color_gradient(low="red", high="blueviolet")
#Add Title to plot
mp <- mp + ggtitle("ColumbiaX: DS101X Users - World Map")

#Create Canvas
x11()
#Plot map
mp
```

```{r}
###Remove India and US
#Load Data
df = read.csv("Merged-1.csv", header=T)
#Remove US Row
df = df[c(-177),]
#Remove India Row
df = df[c(-81),]

# Get World map
worldmap <- map_data("state")
#Prepare the Borders
mapWorld <- borders("world", colour="dark blue", fill="black") 
# Draw the map and mapWorld to show background map
mp <- ggplot() +   mapWorld
#Plot points related to latitude and longitude, with the size and color based on the count
mp <- mp + geom_point(data = df, aes(x = Longitude, y = Latitude, size = count, color = count, label = country.name)) 
#Scale the color based on a gradient from yellow as low to orange as
mp <- mp + scale_color_gradient(low="red", high="blueviolet")
#Add Title to plot
mp <- mp + ggtitle("ColumbiaX: DS101X Users - World Map")

#Create Canvas
x11()
#Plot map
mp
```


#Scatter Plots
```{r}
#Load Data
df = read.csv("Merged-1.csv", header=T)

#Create sequene of numbers from 1 to the number of rows in the Data Frame
xaxis = c(1:nrow(df))

#Create Canvas
x11()

#Create Plot
ggplot(df, aes(x=xaxis, y=(count), size=count, label=country.name),guide=FALSE)+
  #Create Points
  geom_point(colour="white", fill="blue", shape=21)+ 
  #Add X Label
  xlab("Country")+
  #Add Y Label
  ylab("Count")+
  #Add Main Title
  ggtitle("ColumbiaX: DS101X Users")+
  #Add Labels to Bubbles
  geom_text(aes(x=xaxis,y=(count),label=country.alpha3),size=2, hjust = 0.5, vjust = 2)
```

#Scatter Plots - Log

```{r}
df = read.csv("Merged-1.csv", header=T)

#Create sequene of numbers from 1 to the number of rows in the Data Frame
xaxis = c(1:nrow(df))

#Create Canvas
x11()

#Create Plot
ggplot(df, aes(x=xaxis, y=log(count), size=count, label=country.name),guide=FALSE)+
  #Create Points
  geom_point(colour="white", fill="blue", shape=21)+ 
  #Add X Label
  xlab("Country")+
  #Add Y Label
  ylab("Count")+
  #Add Main Title
  ggtitle("ColumbiaX: DS101X Users")+
  #Add Labels to Bubbles
  geom_text(aes(x=xaxis,y=log(count),label=country.alpha3),size=2, hjust = 0.5, vjust = 2)
```