---
title: "GoogleVis"
author: "Bob Minnich"
date: "December 30, 2015"
output: html_document
---

```{r}
library(googleVis)
setwd('/Users/bobminnich/Documents/Columbia/edX Course')

#Load Data
df = read.csv("Merged-1.csv", header=T)

#Create numbered rows for Data Frame, df, so that we can use this for the x-axis in the Bubble Plot
xaxis = seq(1,nrow(df))

#Create Log(count) vector to be able more clearly display data
logcount = log(df$count)

#Add xaxis and logcount to df Data Frame
df = cbind(df,xaxis, logcount)

```

#Create Bubble Chart using Country Codes
```{r}
Bubble <- gvisBubbleChart(df, idvar="country.alpha3", 
                          xvar="xaxis", yvar="logcount",
                          colorvar="count", sizevar="count",
                          chartid="Bubble_Chart",
                          options=list(
                            colorAxis="{colors: ['lightblue', 'blue']}",
                            vAxis="{title:'User Count (Log)'}",
                            hAxis="{title:'Countries'}",
                            width=1000, height=1000,
                            bubble="{textStyle:{color: 'blue',fontName: 'Times-Roman', fontSize:12}}",
                          explorer= "{actions: ['dragToZoom', 'rightClickToReset'] }", 
                          title = "ColumbiaX: DS101X Users Bubble Chart"
                          ))
plot(Bubble)
```

#Create Column Chart using all Countries
```{r}
#Creat Column Chart 
Column_all <- gvisColumnChart(df, xvar = "country.alpha3", yvar = "count",
                          chartid="Column_Chart_All",
                          options=list(
                            vAxis="{title:'User Count'}",
                            hAxis="{title:'Countries'}",
                            width=1000, height=1000,
                            title = "ColumbiaX: DS101X Users Bar Chart"
                            ))
plot(Column_all)
```


#Create Column Chart using Top 50
```{r}
#Creat Column Chart 

#Create a set of row numbers, that are ordered by the Count Column in decreasing order
Row_sort_count = order(df$count, decreasing = TRUE)

#Create New Dataframe that uses the ordering based on Count
newdata <- df[Row_sort_count,] 

#Create Column Chart that has the top 50 countries with the highest users so we can have better resolution. We use 1:50 to access the first 50 rows
Column_50 <- gvisColumnChart(newdata[1:50,], xvar = "country.alpha3", yvar = "count",
                          chartid="Column_Chart_50",
                          options=list(
                            vAxis="{title:'User Count'}",
                            hAxis="{title:'Countries'}",
                            width=1000, height=1000,
                            title = "ColumbiaX: DS101X-Top 50 Bar Chart"
                            ))
plot(Column_50)
```


#Create Column Chart using the rest of countries
```{r}
#Create Column Chart that has the rest of the countries with the highest users so we can have better resolution. We use 51:nrow(newdata) to access the rows of 51:188,  nrow(newdata) = 188

Column_other <- gvisColumnChart(newdata[51:nrow(newdata),], xvar = "country.alpha3", yvar = "count",
                          chartid="Column_Chart_other",
                          options=list(
                            vAxis="{title:'User Count'}",
                            hAxis="{title:'Countries'}",
                            width=1000, height=1000,
                            title = "ColumbiaX: DS101X - Rest of Users Bar Chart"
                            ))
plot(Column_other)
```


#Create Pie Chart
```{r}
#Use tapply to use the Sum function to apply to Region and Count. This will count all of the counts, for each region.
numvar = as.vector(tapply(df$count, df$Region, FUN=sum))

#Create list of Unique Regions to use as labels for Pie Chart
labelvar = as.character(sort(unique(df$Region)))

#Create new Data Frame to use in Pie Chart
ndf = data.frame(labelvar,numvar)
Pie <- gvisPieChart(ndf,
                    options=list(
                        pieStartAngle = 270,
                        width=800,
                        height=800,
                        #Make slice 4 (Europe) that have an offset for visual affects. It is 4 because it is the 4th Region that appears in labelvar.
                        slices="{4: {offset: 0.2}}",
                        title='ColumbiaX: DS101X Users Pie Chart: Region',
                        legend='none',
                        pieSliceText='label',
                        pieHole=0.5,
                        pieSliceTextStyle="{color: 'white',fontName: 'Times-Roman', fontSize:14}"),
                      chartid="doughnut")
plot(Pie)
```

